import type { ContactRow } from "./contacts-table";

export const SAMPLE_CONTACTS: ContactRow[] = [
  {
    id: "1",
    name: "Sarah Parker",
    nameInitial: "S",
    avatarColor: "blue",
    type: "Parent/Guardian",
    email: "sarah.parker@gmail.com",
    phone: "+1 (415) 555-0182",
    source: "Inquiry form",
    engagementScore: "Hot",
    pipelineStage: "Application",
    staffRep: "Oliver Stone",
    staffRepInitial: "O",
    tags: [{ label: "Intake 2026", variant: "teal" }],
    addedAt: "2025-11-12",
  },
  {
    id: "2",
    name: "James Nguyen",
    nameInitial: "J",
    avatarColor: "yellow",
    type: "Parent/Guardian",
    email: "james.nguyen@outlook.com",
    phone: "+1 (628) 555-0143",
    source: "Event registration",
    engagementScore: "Warm",
    pipelineStage: "Onboarding",
    staffRep: "Lucas Taylor",
    staffRepInitial: "L",
    tags: [{ label: "Cycle 2025-26", variant: "violet" }],
    addedAt: "2025-10-03",
  },
  {
    id: "3",
    name: "Ethan Parker",
    nameInitial: "E",
    avatarColor: "green",
    type: "Student",
    email: "ethan.parker@gmail.com",
    source: "Application",
    engagementScore: "Warm",
    pipelineStage: "Application",
    staffRep: "Emma Johnson",
    staffRepInitial: "E",
    tags: [{ label: "Grade 6", variant: "blue" }],
    addedAt: "2025-11-12",
  },
  {
    id: "4",
    name: "Li Wei Education Agency",
    nameInitial: "L",
    avatarColor: "blue",
    type: "Agent",
    email: "contact@liwei-edu.com",
    phone: "+65 9123 4567",
    source: "Manual entry",
    engagementScore: "Hot",
    pipelineStage: undefined,
    tags: [
      { label: "Asia Pacific", variant: "teal" },
      { label: "Priority", variant: "yellow" },
    ],
    addedAt: "2025-09-18",
  },
  {
    id: "5",
    name: "Dr. Amara Osei",
    nameInitial: "A",
    avatarColor: "yellow",
    type: "Recommender",
    email: "a.osei@greenwood.edu",
    source: "Staff referral",
    engagementScore: "Cold",
    pipelineStage: undefined,
    tags: [],
    addedAt: "2025-08-22",
  },
  {
    id: "6",
    name: "Maple Ridge School",
    nameInitial: "M",
    avatarColor: "green",
    type: "Feeder School Contact",
    email: "admin@mapleridge.ca",
    phone: "+1 (604) 555-0211",
    source: "Import",
    engagementScore: "Warm",
    pipelineStage: undefined,
    tags: [{ label: "Partner School", variant: "blue" }],
    addedAt: "2025-07-14",
  },
  {
    id: "7",
    name: "Liam Johnson",
    nameInitial: "L",
    avatarColor: "red",
    type: "Student",
    email: "liam.johnson@gmail.com",
    source: "Application",
    engagementScore: "Hot",
    pipelineStage: "Onboarding",
    staffRep: "Lucas Taylor",
    staffRepInitial: "L",
    tags: [
      { label: "Grade 4", variant: "teal" },
      { label: "Mid-Year Entry", variant: "blue" },
    ],
    addedAt: "2025-10-30",
  },
  {
    id: "8",
    name: "Priya Sharma",
    nameInitial: "P",
    avatarColor: "blue",
    type: "Parent/Guardian",
    email: "priya.sharma@icloud.com",
    phone: "+44 7700 900123",
    source: "Chatbot",
    engagementScore: "Cold",
    pipelineStage: undefined,
    tags: [],
    addedAt: "2025-12-01",
  },
  {
    id: "9",
    name: "Marcus Williams",
    nameInitial: "M",
    avatarColor: "yellow",
    type: "General",
    email: "marcus.williams@company.com",
    source: "Marketing list",
    engagementScore: "Unknown",
    pipelineStage: undefined,
    tags: [{ label: "Newsletter", variant: "gray" }],
    addedAt: "2026-01-09",
  },
  {
    id: "10",
    name: "Olivia Smith",
    nameInitial: "O",
    avatarColor: "green",
    type: "Student",
    email: "olivia.smith@gmail.com",
    source: "Application",
    engagementScore: "Warm",
    pipelineStage: "Application",
    staffRep: "Emma Johnson",
    staffRepInitial: "E",
    tags: [{ label: "Grade 5", variant: "teal" }],
    addedAt: "2025-11-28",
  },
];
